# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
encoding:         UTF-8

# Custom vars
current_version:  0.1.0-rc1
repo:             https://github.com/newsdev/adcom
homepage:         https://newsdev.github.io/adcom/
# homepage:         /

download:
  source:         https://github.com/newsdev/adcom/archive/v0.1.0-rc1.zip
  dist:           https://github.com/newsdev/adcom/releases/download/0.1.0-rc1/adcom-v0.1.0-rc1-dist.zip
