# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
encoding:         UTF-8

# Custom vars
current_version:  0.1.0-rc.16
repo:             https://github.com/newsdev/adcom
homepage:         /adcom/

download:
  source:         https://github.com/newsdev/adcom/archive/v0.1.0-rc.16.zip
  dist:           https://github.com/newsdev/adcom/releases/download/v0.1.0-rc.16/adcom-0.1.0-rc.16-dist.zip
